### ISSUE TITLE
Configuration for getting Interactive metrics in the result?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/wptagent#103]
Hi Pat,
what is needed to get the different interactive metrics as described in https://github.com/WPO-Foundation/webpagetest/blob/master/docs/Metrics/TimeToInteractive.md ?

Today we have **enable_agent_processing=1** but maybe we need something more?

Right now we only get LastInteractive in the JSON that we use, but we miss the others. Some time ago I know it worked for us getting FirstInteractive,TimeToInteractive,LastInteractive but maybe the names/configuration has changed?

In the result HTML page we have the First Interactive metric:
http://wpt.wmftest.org/result/180420_NN_H0/

But in the result we only have LastInteractive:
http://wpt.wmftest.org/xmlResult/180420_NN_H0/

Or is it the iteractive periods that should be used?

Best
Peter

**Comment by pmeenan** [comment]
The main thing that is needed is for timeline capture to be enabled (timeline=1) so it can see the main thread activity.  For Firefox and Edge it should be available even without timelines (uses RAF to check for main thread responsiveness).

As far as what is displayed in the UI, if the actual FirstInteractive wasn't available because there wasn't 5 seconds of idle in the test the UI falls back to using the lastInteractive time and putting a > in front of it.  BAsically, if the page continued to remain idle that would have been the First Interactive time and it wouldn't be any earlier.

Agent processing should largely happen regardless of the flag with wptagent (it is mostly for wptdriver which didn't originally ship with python to do the processing).
