### ISSUE TITLE
[Question] Should the default framerate be higher?

### ISSUE THREAD

**Issue by wildlyinaccurate** [WPO-Foundation/wptagent#109]
The default framerate for ffmpeg capture is 10fps. This makes visual metrics like start render and visually complete only accurate to within 100ms. I realise there will be tradeoffs in terms of video size and impact on system resources, but it would be nice if these metrics could have a higher level of accuracy.

**Comment by pmeenan** [comment]
You can specify a higher framerate on a per-test basis with the "fps" parameter (through the API).  For one-off testing you can pass fps=30 as a query param to the main [WebPageTest UI](https://www.webpagetest.org/?fps=30) before requesting a test to override it.

If you are running a private instance and would like to set it system-wide I can see about creating a settings for settings.ini to allow for a global fps default.

The concern isn't with video size or anything related to the processing.  Higher framerates start to impact the performance of the actual test because of CPU contention with the video capture so it is a balancing act to get accurate measurements without impacting the actual testing (or at least minimizing the impact).

**Comment by wildlyinaccurate** [comment]
I was mainly thinking about the default for webpagetest.org, rather than private instances. I think 100ms is definitely accurate enough for most cases but on fast pages it would be nice to have those extra frames. [Here's a super-contrived example](https://www.webpagetest.org/result/180502_AK_79252bc628cc3780d2b4a540133fd412/) of a fast site on fibre -- I would guess the start render numbers are off by about 30%.

It's good to know that the FPS can be specified via the UI. I will run some tests on webpagetest.org to try and measure what sort of impact there would be from bumping the rate to 15 or 20 FPS (66ms / 50ms accuracy).
