### ISSUE TITLE
webpagetest login script not work

### ISSUE THREAD

**Issue by cpselvis** [WPO-Foundation/wptagent#139]
The following is script, How can this work well?

logData 0
navigate http://id.qq.com/login/ptlogin.html
setValue id=u testusername
setValue id=p testpassword
submitForm id=loginform
logData 1
navigate http://id.qq.com/index.html
setViewportSize 375 813
setUserAgent Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25

**Comment by pmeenan** [comment]
When I navigate to http://id.qq.com/login/ptlogin.html namually I don't see a form for logging in.

Your best bet is to use javascript with the exec/execAndWait commands and first get the javascript working in a local browser in dev tools.

On a separate note, the viewport and UA string need to be specified at the beginning of the script, otherwise they aren't going to do anything.

**Comment by cpselvis** [comment]
How can I use script to click a button in a iframe?

**Comment by cpselvis** [comment]
This problem is solved
