### ISSUE TITLE
Mobile emulation broken on the latest WPTAgent?

### ISSUE THREAD

**Issue by SankaitLaroiya** [WPO-Foundation/wptagent#146]
Hi,

When I run a test which emulates mobile (Chrome/Firefox) on a dockerized agent in Linux, I get an error saying that the browser crashed and no metrics are collected. The screenshot is missing as well, however, I can see the waterfall and the video/film strip. 

Firefox doesn't collect any metrics (Desktop or mobile)

Screenshots attached:
https://i.imgur.com/1CHB66G.png
https://i.imgur.com/5FkAEBQ.png

**Comment by pmeenan** [comment]
For Firefox, do you mean the optimization checks?  All of the metrics look fine.  Optimization checks aren't supported on Firefox because there is no way to get the response bodies.

As for Chrome, try capturing the debug log (?debug=1 on the url for the landing page for submitting tests will turn it on and then it will be available in the results as a link to the left of the waterfall).  As far as I know, mobile emulation is working fine and there isn't anything specific to running in a docker container that should change that.

**Comment by pmeenan** [comment]
btw, mobile emulation is a Chrome-only thing.

**Comment by SankaitLaroiya** [comment]
In the first screenshot, I ran a test using FireFox. It doesn't show the Grades on the top. 
Also, I tried capturing the debug log on Chrome (mobile emulation) and it shows that the agent doesn't try to run lighthouse test. It works fine for desktop mode.

**Comment by pmeenan** [comment]
Grades (optimization checks) aren't available for Firefox.  All of the actual loading metrics are though.

For the mobile emulation run, was lighthouse enabled (through UI or lighthouse=1 through API)?  Did the non-lighthouse test before the lighthouse run complete successfully?  There's a good chance the agent only runs lighthouse if the page loaded successfully during normal testing.

**Comment by SankaitLaroiya** [comment]
I found the issue. Its not the code. I deployed the agents on AWS (can't use the AMI due to company policy) and the ALB that was being used was not configured properly. Sorry for the misunderstanding. Thanks!
