### ISSUE TITLE
'setDnsName' not taken into account by lighthouse reports

### ISSUE THREAD

**Issue by jeromelachaud** [WPO-Foundation/wptagent#163]
Could that be possible that the 'setDnsName' method is taken into account in the lighthouse reports ? 
, like it's the case for WPT reports.
If you look at those two LH reports, they are exactly the same:
https://wpt.fasterize.com/lighthouse.php?test=180727_DT_5X
https://wpt.fasterize.com/lighthouse.php?test=180727_YW_5Z

Thank you :grin:

**Comment by abarre** [comment]
This seems possible to use the --chrome-flags for this case.
A similar need has been implemented : https://github.com/WPO-Foundation/wptagent/pull/178.

**Comment by pmeenan** [comment]
Thanks for the ping because the other fix shouldn't work either - WPT launches Chrome itself.  WPT launches the browser and passes it over to Lighthouse to run the test.  That said, fixing it as a flag (and a host mapping) when wptagent launches Chrome should work.

**Comment by abarre** [comment]
Thanks @pmeenan, for the details.
Do you mean that the current implementation should already work since lighthouse is launched by Chrome and so reuses flags set for Chrome ?

By the way, do you know if lighthouse is started before or after other runs ? I guess that it is launched at the end.

One example showing the issue : http://wpt.fasterize.com/result/180916_Q8_5/ and http://wpt.fasterize.com/result/180915_XM_3PK/ and http://wpt.fasterize.com/result/180916_ME_9/.

**Comment by abarre** [comment]
I confirm that there is no bug. `setDnsName` is correctly taken into account.
