### ISSUE TITLE
Run custom "hero" elements standalone without default "heroes"

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/wptagent#169]
Hey @pmeenan @wildlyinaccurate I want to suggest a change in how the custom "hero" elements work. At the moment the flow is like this:
Loop through all elements on the page, search for img, h1/h2, background images and attribute element timing. Then use custom selectors to get specific elements.

I want to change this so that if the user add custom selectors only those elements are used. That way we will get rid of the loop of all elements (for https://en.wikipedia.org/wiki/Barack_Obama that is 16000+ elements). On the machine that I tested on that loop adds quite much overhead in total test time. 

And I think if the user chooses to configure custom elements she/he can choose exactly the elements that is needed and there's no need for the automatic catch of metrics?

I'll do a PR and you can discuss if this is fine for you :)

Best
Peter

**Comment by wildlyinaccurate** [comment]
I'm surprised to hear that the loop adds overhead in your tests. Do you mind me asking what your test setup is? I mostly tested this on my Raspberry Pi 2, and the hero element overhead was about 6 seconds including the Python code that does the frame-by-frame image analysis. On our EC2 WPT agents (c4.large) the overhead is more like 2 seconds.

The only problem I have with #170 is that it would make it impossible to have the default elements _and_ custom elements. The default elements are "special" in that they find the largest of each heading, image, and background image, so it's not enough to just have add a custom element with "h1" as the selector.

Maybe an extra boolean attribute to disable the default hero elements would be better? Although I'm still very curious to know what it is about your test setup that causes this code to add so much overhead!

**Comment by pmeenan** [comment]
If the JS is taking a long time to run (maybe on a mobile device or when CPU throttling is active) I'd love to see if there is anything we could do to optimize the search so maybe it didn't have to look at all 16000+ elements (maybe with a query selector of some kind).

**Comment by wildlyinaccurate** [comment]
The background image detection is the only reason to enumerate every node in the document, since there's no way (that I know of..?) to select only elements with a background image. I ran a few benchmarks on my RPi 2. The average run time for the JS on https://en.wikipedia.org/wiki/Barack_Obama is 380ms. Without the background image detection it's 10ms.

The real issue is calling `getBoundingClientRect()` on every node. It's much quicker to use `IntersectionObserver` but I'm not sure how to deal with it being async. Is there a synchronous way to check whether an element is in the viewport that is quicker than `getBoundingClientRect()`?

**Comment by pmeenan** [comment]
What happens if you check for a background image before checking for the rect?  Or check for visibility first? Might not be any faster if it is forcing a style calculation but maybe there are some lightweight filters that can help make it faster. That said, it still doesn't seem to be the likely root cause.

________________________________

**Comment by soulgalore** [comment]
Sorry for not getting back so fast. I was actually running in Docker on my local computer when I felt the slowness but I didn't actually measure it. It is probably an indicator that I need to buy a new desktop computer :)

When I tried it out on c4.large testing 31 URLs 5 runs each (some of them is the mobile site though, less elements) the total test time increased with 11 minutes (18% increase). That's the total time though so the extra time in Visual Metrics is also included. That is ok though I think, but it would interesting to measure the time to pick only custom metrics to see if there's any difference.

**Comment by wildlyinaccurate** [comment]
@soulgalore that's a much larger increase in test time than I would expect. I would be interested to know how much of that time is spent in the JS versus in visual_metrics.py. I have been wondering whether the visual processing can be optimised by performing an exponential binary search on the frames rather than running through them sequentially.

**Comment by pmeenan** [comment]
I was thinking about it and a binary search could fail if the hero element paints, something pops up and it comes back.  It could accidentally pick the second paint time.  That said, the Wikimedia pages tend to have very few frames in them so getting a failcase along with debug logging (both on and off) could really help.

**Comment by pmeenan** [comment]
Sorry, just catching up on open PR's and issues.  Is this still a problem or has it largely been absorbed? If there's still optimization work to be done I'm happy to leave the issue open.

**Comment by soulgalore** [comment]
I haven't looked into it. I think we can close it.
