### ISSUE TITLE
Tracking down increased scripting CPU time

### ISSUE THREAD

**Issue by wildlyinaccurate** [WPO-Foundation/wptagent#269]
Around the same time that [V8 runtime call statistics were enabled](https://github.com/WPO-Foundation/wptagent/commit/4f088f374f5fe242946719e994235bf9a308d064) we noticed a jump in the amount of CPU time being recorded in script_timing.json.

If I'm following the code correctly, including the runtime call stats in the trace shouldn't affect how the script timing is calculated, should it?

**Comment by pmeenan** [comment]
It shouldn't but if it looks like it made the actual script execution
slower (more overhead) I can disable it by default ant turn it on with a
targeted test option.

**Comment by wildlyinaccurate** [comment]
I'll try to do some more benchmarking. The "collecting trace events" post processing takes about 3x longer on my raspberry pi agent with the runtime call stats enabled, so I can imagine there's a bit of overhead during the test run with the extra tracing.

**Comment by wildlyinaccurate** [comment]
Hmm, seems like if I remove `disabled-by-default-v8.runtime_stats` from the trace categories then no main thread processing data is gathered at all. Is that expected?

**Comment by wildlyinaccurate** [comment]
Ah, nope, that's because I removed the `v8` category as well. I don't know how representative this is, but I ran a bunch of tests against one URL (https://www.asos.com/) with and without the `disabled-by-default-v8.runtime_stats` trace category. The average scripting time without was 1700ms and with was 2600ms.

Being able to disable that category without wptagent adding it back in would be useful, even if just to confirm this at a larger scale.

**Comment by pmeenan** [comment]
Removing the v8 category is expected and it shouldn't be used for normal JS timings.  I just pushed a change to remove RCS by default and exposed it as an explicit test option (v8rcs) and it toggles both the v8 and v8...... trace options.

That said, I ran CNN with/without RCS and didn't see any appreciable differences: https://www.webpagetest.org/video/compare.php?tests=190627_Tx7H_8e2d5d7f51a80c8c4403c2e4a199cdfa,190627_TxQB_686ae3ad2d9c14acbbb3bc88eea53ac1

Given the JS nightmare that it is I would have expected any RCS issues to jump out. Maybe the site you are testing is triggering a pathalogical behavior or something else is going on?

FWIW, One big change to main-thread times recently was to improve/fix the main thread detection because Chrome is labeline a lot of different processes as the "main" one (site isolation) so if the overall page time didn't change jut the JS times got longer it is likely a result of better logic for selecting the main thread.

**Comment by wildlyinaccurate** [comment]
Thanks, I'll take a look at some aggregate results later today and see if it made a difference.

> FWIW, One big change to main-thread times recently was to improve/fix the main thread detection because Chrome is labeline a lot of different processes as the "main" one (site isolation) so if the overall page time didn't change jut the JS times got longer it is likely a result of better logic for selecting the main thread.

Yeah, I thought it might have been that initially. The thing that seemed fishy was that almost every metric had a slight increase around the date of the V8 trace category commits, with JS time being the most pronounced.

**Comment by wildlyinaccurate** [comment]
That change certainly made a difference - thanks!
