### ISSUE TITLE
Extract Chrome's Largest Contentful Paint metric

### ISSUE THREAD

**Issue by foolip** [WPO-Foundation/wptagent#277]
The new [Largest Contentful Paint](https://wicg.github.io/largest-contentful-paint/) metric is [shipping in Chrome 77](https://bugs.chromium.org/p/chromium/issues/detail?id=965505), and it would be great to have this metric available in httparchive data, which requires support in WebPageTest.

I'm new to this project, but it looks like there are a few possible places where this could go:

https://github.com/WPO-Foundation/wptagent/blob/04f5856297d0828b70462bc6b3b67a0343dacfb5/internal/support/devtools_parser.py#L998-L1010

https://github.com/WPO-Foundation/wptagent/blob/6084647fed49617201419a559cc41940ee0e5cfa/internal/js/page_data.js#L19-L26

https://github.com/WPO-Foundation/wptagent/blob/04f5856297d0828b70462bc6b3b67a0343dacfb5/internal/support/trace_parser.py (maybe?)

@pmeenan @rviscomi @tdresser

**Comment by foolip** [comment]
A problem with page_data.js is that it's entirely synchronous, and LCP requires the use of `PerformanceObserver` which is callback-based. Since the LCP can keep changing as time passes, I think one would have to add the observer as early as possible, and keep the last entry right before the testing session (?) is stopped.

**Comment by foolip** [comment]
Grepping a verbose trace from chrome://tracing I found that there's a "[NavStartToLargestContentfulPaint::Candidate::AllFrames::UKM](https://cs.chromium.org/chromium/src/chrome/browser/page_load_metrics/observers/ukm_page_load_metrics_observer.cc?l=639&rcl=5c7ef4fd5783791e9a7d08c07716f8e21d3b0ca6)" trace event that could probably be used here. This was added in https://chromium-review.googlesource.com/c/chromium/src/+/1671027 by @maxlgu and reviewed by @bryanmcquade. This tracing event was clearly added for UKM, but would it be a bad idea to use it in WebPageTest? Are there other better ways to get this information out?

**Comment by maxlgu** [comment]
Yes we can use this trace event for WebPageTest. It doesn't rely on PerformanceObserver, though LCP as well as FP, FCP, FMP, depends on "swap-time callback" to get the paint-time. But I believe this callback should have no problem working with WebPageTest because otherwise we wouldn't have got FP, FCP, FMP right.

This event is what we plan to use to surface to devtool's tracing UI - crbug.com/956152. Be sure to consider both "NavStartToLargestContentfulPaint::Candidate::AllFrames::UKM" and "NavStartToLargestContentfulPaint::Invalidate::AllFrames::UKM", rank them by event.start, and take the last event. If the last event is the "invalidate" one, then discard the result. Otherwise (the "Candidate" case), then take event.data.durationInMilliseconds as the LCP time.

**Comment by pmeenan** [comment]
FWIW, I'd rather not use the duration directly from the trace event but use the trace event timestamp relative to the same baseline used for the rest of the results data and waterfall.  The main reason is for pages that do a javascript redirect, that looks like a new navigation to Chrome but is still part of the same page load for WPT and I want the redirect time to be included.

If the last event is an invalidate does that mean there is no LCP or that it should fall back to the previous candidate and just invalidate the most recent?  i.e. do I keep a single candidate that I update/delete or do I keep a stack where I pop a result off each time something gets invalidated?

**Comment by rviscomi** [comment]
@igrigorik fyi

**Comment by pmeenan** [comment]
FWIW, the [custom metrics](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/custom-metrics) support running async code in Chrome. If the metric returns a promise it will wait up to 30 seconds to resolve the promise and use that. I believe @rviscomi has used it with performance observer (in buffered mode which lets you go back in time) to collect similar metrics.

It might just be easier to add it to our collection of custom metrics scripts that we use with HA.

While working on the script you can test it by submitting the script as a one-off custom metric on the public WPT using Canary (or Beta if 77 is on beta) to make sure it works first.

I still want to add the trace-based metric as well because of the timestamp issue above but there's also no harm in having both.

**Comment by tdresser** [comment]
If the last event is an invalidate, it implies that there's an image that
we know about that hasn't been displayed yet, which is larger than all
displayed images. In this case, we're unable to compute LCP, as we know
that it should occur at some point in the future.

+Liquan (Max) Gu <maxlg@google.com>to confirm that this is the only case.

Patrick Meenan wrote:

**Comment by maxlgu** [comment]
Thanks for raising the issue, I've just created a bug for it - crbug.com/989583.

> If the last event is an invalidate does that mean there is no LCP or that it should fall back to the previous candidate and just invalidate the most recent? i.e. do I keep a single candidate that I update/delete or do I keep a stack where I pop a result off each time something gets invalidated?

If the last event is an invalidate, there is no LCP. For example, when a page takes down the splash screen, the LCP should be reset to null at this moment.

**Comment by maxlgu** [comment]
Send before seeing @tdresser 's response. And yes, a loading image, as well as content removal, can  invalidate the LCP result.

**Comment by pmeenan** [comment]
ok, should be live on the public instance within the next hour or so (if you test with Canary). It will show up in the HTTP Archive in the September Crawl which should be the first crawl after 77 launches:

```json
"_chromeUserTiming.redirectStart": 5,
"_chromeUserTiming.redirectEnd": 110,
"_chromeUserTiming.fetchStart": 110,
"_chromeUserTiming.unloadEventStart": 260,
"_chromeUserTiming.unloadEventEnd": 260,
"_chromeUserTiming.domLoading": 6154,
"_chromeUserTiming.markAsMainFrame": 260,
"_chromeUserTiming.responseEnd": 6155,
"_chromeUserTiming.firstLayout": 6171,
"_chromeUserTiming.domInteractive": 6155,
"_chromeUserTiming.domContentLoadedEventStart": 6155,
"_chromeUserTiming.domContentLoadedEventEnd": 6155,
"_chromeUserTiming.firstPaint": 6380,
"_chromeUserTiming.firstContentfulPaint": 6380,
"_chromeUserTiming.firstMeaningfulPaintCandidate": 7131,
"_chromeUserTiming.LargestTextPaint::Candidate": 2566,
"_chromeUserTiming.firstMeaningfulPaint": 7131,
"_chromeUserTiming.LayoutShift": 9560,
"_chromeUserTiming.LargestImagePaint::NoCandidate": 9602,
"_chromeUserTiming.firstImagePaint": 6380,
"_chromeUserTiming.LargestImagePaint::Candidate": 9617,
"_chromeUserTiming.domComplete": 9775,
"_chromeUserTiming.InteractiveTime": 10176,
"_chromeUserTiming.loadEventStart": 9775,
"_chromeUserTiming.loadEventEnd": 9937,
"_chromeUserTiming.LargestContentfulPaint": 15931,
```

Looks like there is some noise with the text/image candidates that could use some cleaning up but I'm not too worried about letting them leak through for now.

**Comment by foolip** [comment]
@pmeenan fantastic, this was the best bug filing experience in a while!

Do you have a pointer to the changes you made here and in httparchive? I'm curious to see how this is all wired together.

**Comment by maxlgu** [comment]
Just to make sure we agree on "some noise with the text/image candidates" here.

"LargestImagePaint::NoCandidate" (sorry for the confusing name) plays the role of invalidating the existing "LargestImagePaint::Candidate". The simple algorithm to get the final result is that:
if "NoCandidate">"Candidate" return null;
else return "Candidate";

**Comment by pmeenan** [comment]
@maxlgu Yes, sorry - "some noise" is because I just dump all of the trace events from the rail and loading categories that are emitted for the main frame. The "noise" is just in the WPT results because I added special logic for LCP but not the others. At some point I should add the candidate/invalidate logic for filtering the others as well.

@foolip [here](https://github.com/WPO-Foundation/wptagent/commit/7eb257c5af2566ddc335b797a06e21dc4440e41f) is the agent-side change. There was also a server-side change [here](https://github.com/WPO-Foundation/webpagetest/commit/6e947a6692512658ebef4f2639205158d9b0789a) to include the new trace events because they indicate the frame differently from others.

**Comment by bryanmcquade** [comment]
@pmeenan you'd mentioned "I'd rather not use the duration directly from the trace event but use the trace event timestamp relative to the same baseline used for the rest of the results data and waterfall" - did you end up using the trace event timestamps for this? I am not deeply familiar with how tracing works but if the trace event timestamps are set when the trace event is recorded, then the trace event timestamp would not be the correct value for LCP, as we buffer LCP and similar metrics before recording it.

@maxlgu @tdresser can you take a look at the agent-side change:
https://github.com/WPO-Foundation/wptagent/commit/7eb257c5af2566ddc335b797a06e21dc4440e41f

To make sure the logic is consistent w/ how your LCP trace event processing works?

**Comment by maxlgu** [comment]
@bmeurer, @hashseed and I are working together to add a renderer side LCP event, the discussion lives in here - crbug.com/956152, crbug.com/989583 and the CL lives in crrev.com/c/1745433, and @hashseed's proof of concept lives in crrev.com/c/1745995

> I am not deeply familiar with how tracing works but if the trace event timestamps are set when the trace event is recorded, then the trace event timestamp would not be the correct value for LCP, as we buffer LCP and similar metrics before recording it.

Actually the tracing has an event called TRACE_EVENT_INSTANT_WITH_TIMESTAMP which can fires an event in an arbitrary time. Currently the LCP time lives in  of the LCP event. For the new renderer LCP in the WIP CL, the LCP time will live in the event timestamp.

@pmeenan, for the PR, I see that it is using "event.startTime" as LCP, but instead we should use "event.args.data. durationInMilliseconds". Be aware that durationInMilliseconds is a duration from navigation start to LCP, not a time-tick type.

**Comment by pmeenan** [comment]
The problem with the duration since the navigation start is that it doesn't
necessarily hold for pages that include a JS redirect or otherwise when
"navigation start" isn't really the start point of the navigation. One
possibility then is to use the durationInMilliseconds within the LCP event
and add it to the event.startTime of the last navigation event on the main
thread.

With TRACE_EVENT_INSTANT_WITH_TIMESTAMP doesn't it still record the event
time as if it fired at the time that the timestamp was passed in and use
that as the trace event timestamp? Otherwise none of the RAIL events that
use it would show up correctly in the trace viewer either.

**Comment by bryanmcquade** [comment]
Thanks @maxlgu! If we don't think the current trace event in WPT is correct, maybe it makes sense to disable it until we have the renderer-based traces in place. If the renderer-based implementation is likely to take a while to complete, we could consider improving the existing UKM-based trace events in the interim.

**Comment by maxlgu** [comment]
@skobes has landed the renderer-based trace - https://chromium-review.googlesource.com/c/chromium/src/+/1745433.

**Comment by anniesullie** [comment]
What's the status here? I am trying to compare LCP to other metrics in the HttpArchive October run, and seeing values of LCP that are much less than FP/FCP. Digging into a few, it seems like the pages have JS redirects. Was this fixed? If so, which Http Archive release would it be fixed in?

**Comment by pmeenan** [comment]
I just added logic to the WebPageTest side to prefer the renderer-side trace events so earliest would be the November crawl (most of it since it started a few days ago). Complete crawl with the renderer-side version of the metric won't be until the December Crawl.

**Comment by anniesullie** [comment]
Thanks, @pmeenan that's super helpful!
