### ISSUE TITLE
Late First CPU Idle times

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/wptagent#288]
Hi @pmeenan,

We're seeing a few tests where First CPU Idle appears to be firing late and not correlating with the interactive periods shown below the waterfall.

In this [example](https://wpt1.speedcurve.com/details.php?test=190926_G4_0a1b4601b16cf256c06e5b45e00f6e34&run=2#waterfall_view_step1) the FCI is reported at 15.1s but the last blocking CPU period ends at 12s.

Here's a [run on public](https://www.webpagetest.org/result/190929_ZB_b3cda53c074374b4443e2ced4cda8d94/1/details/#waterfall_view_step1) where test time was set to minimum 30s and FCI also appears to not match the interactive periods shown. 9s vs 5.5s for the last interactive period.

**Comment by jaybirdonrails** [comment]
Here is another example: https://wpt1.speedcurve.com/details.php?test=191103_RA_c098f6735c16efadb22204ce020bd8ba&run=1#waterfall_view_step1.  First CPU idle shows 13.7s but last blocking CPU was around 10s.

**Comment by pmeenan** [comment]
I wonder if there's a caching problem somewhere and I caused it to regenerate but when I look at the [public run](https://www.webpagetest.org/result/190929_ZB_b3cda53c074374b4443e2ced4cda8d94/1/details/#waterfall_view_step1) I see FCI at 5.5s

![Screen Shot 2019-11-08 at 4 44 18 PM](https://user-images.githubusercontent.com/444165/68512673-0ea74c00-0247-11ea-9963-cb83e6d161f9.png)

Both the waterfall interactive periods and FCI should be calculated from the same underlying data so something bizarre must be going on.

I'll need to reproduce it on the public instance to debug though because the metric is calculated in the php code, not the agent.

**Comment by jaybirdonrails** [comment]
Thanks @pmeenan.  Let me know if more data points from us would help.  This is very impactful to our troubleshooting efforts and our team's primary performance improvement goals. 

We appreciate you looking into it.

**Comment by pmeenan** [comment]
I've run ~200 tests of that page with 4G, emulated iPhone on the public instance and so far all of the FCI times match the interactive times on the waterfall.  If you can reproduce it on the public instance it would really help with the debugging, otherwise I'll need @zeman to add the "Export to..." to the SpeedCurve instance to upload one of those results to the public instance to debug.

**Comment by jaybirdonrails** [comment]
@pmeenan Thanks again for looking into this.

@zeman, would you be able to assist in get one of the results to @pmeenan?  Any idea what might be causing the discrepancy in results between the Speedcurve vs public instances?

Thanks boys,
Simon@Edmunds.

**Comment by zeman** [comment]
@jaybirdonrails I've sent a copy of the WPT result through to Pat to investigate.

**Comment by jaybirdonrails** [comment]
Sweet!  Thanks again guys.

**Comment by zeman** [comment]
@jaybirdonrails should now be fixed. Let us know if you continue to see this issue.
