### ISSUE TITLE
Get response body for Chrome generates errors

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/wptagent#391]
Hi Patrick,
we have had problem with our instance, I could see that the problem started after 20/12-2020 - 00:17 that day. Our Chrome tests stopped to work for most our URLs and on the agent we get errors like:

```
Traceback (most recent call last):
  File "/home/ubuntu/wptagent/internal/webpagetest.py", line 1112, in get_bodies
    json.loads('"' + data.replace('"', '\\"') + '"')
ValueError: Unrecognized escape sequence when decoding 'string'
Error appending bodies
Traceback (most recent call last):
  File "/home/ubuntu/wptagent/internal/webpagetest.py", line 1112, in get_bodies
    json.loads('"' + data.replace('"', '\\"') + '"')
ValueError: Unrecognized escape sequence when decoding 'string'
Error appending bodies
Traceback (most recent call last):
  File "/home/ubuntu/wptagent/internal/webpagetest.py", line 1112, in get_bodies
    json.loads('"' + data.replace('"', '\\"') + '"')
ValueError: Unrecognized escape sequence when decoding 'string'
```

Today when I disabled getting the response body for the tests they started to work again. We haven't touched our instance at that time, and maybe it something got not in sync during an auto update, do you know what it can be?

Best
Peter

**Comment by pmeenan** [comment]
Hmm, something else must be going on. Those specific errors are wrapped in an exception handler so they'll log but they won't actually break anything.  It looks like that can happen in the post-processing body fetching if a non-text response has a text mime type.

If you can capture a full debug log (debug=1 test option if the test completes and uploads but just fails) I can take a look.  Otherwise you'd need to capture the stdout from the agent.

Another possibility, if the tests get picked up but never return is if the server doesn't allow for large enough uploads. There was a recent change to stop uploading each test run separately and it now uploads all of the runs as a single post.  It fixes a lot of race conditions but it does make the test result post significantly bigger (and not storing bodies might get under the threshold).

**Comment by soulgalore** [comment]
Aha ok. I will test with turning on debugging asap. 
Thanks!

**Comment by soulgalore** [comment]
The problem for me is that when I turn on debug log, there's no link to download it in the result when it fails:
<img width="950" alt="Screen Shot 2021-01-09 at 11 40 51 AM" src="https://user-images.githubusercontent.com/540757/104089479-bff0aa00-526f-11eb-866e-66ac7bae7ea1.png">

If I hack the download URL the log doesn't exists so it seems the the communication between the server and the agent doesn't work right?

I could recreate the issue on our instance (but not WebPageTest.org). If I test https://en.wikipedia.org/wiki/Sweden with three runs, everything works fine, but increasing it to five gets the error. Here's and example http://wpt.wmftest.org/result/210109_K1_HQ/

And the error in the test log in the server:
```
2021/01/09 10:23:20 - Extracting  byte uploaded file '' to './results/21/01/09/K1/HQ'
2021/01/09 10:23:20 - Error opening uploaded ZIP file '
```

**Comment by pmeenan** [comment]
That's another sign the server can't handle the file uploads of the test
results and is discarding them. Looking at the /install page it looks like
it is capped at 2MB and an 8MB post:
http://wpt.wmftest.org/install/

I highly recommend making both of them MUCH bigger in php.ini (even bigger
than the 10MB recommended - 50-100MB to make it not a problem ever).

**Comment by soulgalore** [comment]
Ah thanks. I think the server was created with the AWS image a long time ago but maybe we changed the settings along the road.
