### ISSUE TITLE
Second view on Firefox picks up first view

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/wptagent#44]
Hi Pat,
sorry for adding all the issues, I'm testing all our tests now on the agent to see if it would work to switch.

One of our tests access one URL and then the other:
```
logData 0
navigate https://en.wikipedia.org/wiki/Edward_VI_of_England

// Erase the current HTML to make the video easier to understand
exec document.body.innerHTML = "";
sleep	30

logData 1
navigate https://en.wikipedia.org/wiki/Elizabeth_I_of_England
```
The problem is that the first URL is picked up in the waterfall (as the second request) - http://wpt.wmftest.org/result/170904_MC_AB/1/details/#waterfall_view_step1:

<img width="957" alt="screen shot 2017-09-04 at 11 47 52 am" src="https://user-images.githubusercontent.com/540757/30021546-062d5440-9168-11e7-9aed-eb94adb64d58.png">

Best
Peter

**Comment by pmeenan** [comment]
Issues are appreciated.

It's possible that something is going on with the partial processing of the MOZ_LOG file since I have to use byte ranges to select parts of the file to parse for each step but all of the events are timestamped so it would be very bizarre to have the request logged if it didn't really happen.  

It's possible that something is going on with the merging of the extension-logged requests and the ones from the moz_log.  Either way it should be easy enough to reproduce and fix.  I probably won't get to it until tomorrow though since today is a holiday over here.

**Comment by soulgalore** [comment]
Yes this works now, thanks!!!!
