### ISSUE TITLE
FreeBSD bridge setup and configuration

### ISSUE THREAD

**Issue by j0weiss** [WPO-Foundation/wptagent#65]
As we migrate our iOS test setup to use this WPT Agent we would like to use the remote traffic-shaping option of the agent which you documented [here](https://github.com/WPO-Foundation/wptagent/blob/master/docs/install.md#remote-traffic-shaping).

Can you give as some hints on how your setup works? E.g.: do you use a specific piece of hardware to run the FreeBSD bridge?

I'm happy to create some documentation or even a walkthrough as we set up everything.

**Comment by pmeenan** [comment]
I use a pretty ancient [1U supermicro Atom server](https://www.newegg.com/Product/Product.aspx?Item=N82E16816101332) mostly because I wanted something that I could remote manage with the built-in IPMI, 2 network interfaces and low power.  Bridging takes almost no CPU and the D510 is plenty.  There are newer versions that are faster for the same power but pretty much anything with 2 network interfaces will work.

I have an airport extreme (the old hocky puck ones) handling the WiFi because they "just work".

[Air Port] <-> FreeBSD Bridge <-> Main network

I'm running FreeBSD 9.2 mostly because there hasn't been a need to update it.  Things were a bit flaky with 10 but I think they are back under control.

My rc.conf.local:

```
#BRIDGE CONFIG
cloned_interfaces="bridge0"
ifconfig_bridge0="addm em0 addm em1"
ifconfig_em1="up"
ifconfig_em0="inet 192.168.0.X/16"
defaultrouter="192.168.0.1"

#IPFW Config
firewall_enable="YES"
firewall_type="open"
firewall_script="/etc/ipfw.rules"
```

That basically sets up the bridge across the 2 ethernet ports and assigns the bridge interface an address so it can be communicated with.  Then it loads ipfw.rules which is where all of the pipes are set up.

ipfw.rules:

```
ipfw -q flush
ipfw -q pipe flush

# traffic to bypass shaping
ipfw add skipto 60000 proto tcp src-ip 72.66.115.10
ipfw add skipto 60000 proto tcp dst-ip 72.66.115.10
ipfw add skipto 60000 proto tcp src-port 22
ipfw add skipto 60000 proto tcp dst-port 22
ipfw add deny ip from any to any bootps via em1

# Static pipes assigned by IP address to the 192.168.201.x subnet
for i in `seq 2 9`
do
  ipfw pipe $i config delay 0ms noerror
  ipfw pipe 30$i config delay 0ms noerror
  ipfw queue $i config pipe $i queue 100 noerror mask dst-port 0xffff
  ipfw queue 30$i config pipe 30$i queue 100 noerror mask src-port 0xffff
  ipfw add queue $i ip from any to 192.168.201.$i out xmit em1
  ipfw add queue 30$i ip from 192.168.201.$i to any out recv em1
done
for i in `seq 10 90`
do
  ipfw pipe $i config delay 0ms noerror
  ipfw pipe 3$i config delay 0ms noerror
  ipfw queue $i config pipe $i queue 100 noerror mask dst-port 0xffff
  ipfw queue 3$i config pipe 3$i queue 100 noerror mask src-port 0xffff
  ipfw add queue $i ip from any to 192.168.201.$i out xmit em1
  ipfw add queue 3$i ip from 192.168.201.$i to any out recv em1
done

ipfw add 60000 pass all from any to any
```

There is some logic to bypass the pipes for access to the WPT server and for ssh though those aren't really needed anymore since the agent doesn't run on the phones themselves (it's from the old mobitest days).

The main logic is in the loop where it sets up pipes 2-90 and 302-390 as matched pairs and assigns each one of them to traffic going to each of the static IP addresses 192.168.201.2 through 192.168.201.90.

Pipes 2-90 are the inbound pipes for each of the phones and 302-390 are the outbound pipes.

That gives me room for 89 phones before I have to go in and change anything.

I then statically assign address to each of the phones from the 201.x address pool and configure the external shaping with the matching pipe numbers.  i.e. phone 192.168.201.32 gets pipes 32 and 332 (inbound and outbound).

The FreeBSD server is also configured with the public key from the agents so that root access is available remotely over ssh from the agents to be able to configure the pipes.

FWIW, it's going to take a few months before I get back to it but I have a proof-of-concept for reverse tethering the iPhones that works so WiFi and external bridging won't be necessary permanently.

**Comment by j0weiss** [comment]
Wow, thanks for the fast and thorough answer. This looks like a very good starting point.

Also I'm happy to here about your proof-of-concept. Having both, Android and iOS using reverse tethering sounds very neat.

**Comment by j0weiss** [comment]
Closing this, since #220 has a detailed documentation.
