### ISSUE TITLE
Please enable Opera Browser support.

### ISSUE THREAD

**Issue by cesarv76** [WPO-Foundation/wptagent#68]
Hi,

Please add Opera Browser to the android_browsers.json file.

Thanks!

**Comment by pmeenan** [comment]
Support for blackbox testing (like everything except for Chrome on Android) will be landing in a minute.  It is a shame that the remote debug protocol isn't enabled the same way it is for Chrome (and the only documented way to do it doesn't work on recent releases) otherwise we'd get much better test results.
