### ISSUE TITLE
Windows 10, Problem with Edge and IE

### ISSUE THREAD

**Issue by PhilAlbrecht** [WPO-Foundation/wptagent#76]
Hello again,

I am having issues with Edge and Internet Explorer under Windows10. Currently two kinds of errors appear: 
- Test Error: Error starting browser: Message: A window size operation failed because the window is not currently available (only Edge, gets no waterfall result at all.)
- Test Error: Page Load Timeout  (Edge and IE, waterfall appears to be strange.)

The following two screenshots, represent a test on www.google.de with Edge and IE. Page Load Timeout occurred. There seems to be no SSL whatsoever (opposing to ChromeTests). Document Complete and First Interactive seem to be completely off.

**Edge Waterfall**
![edge-error](https://user-images.githubusercontent.com/30042849/35625084-50d642f6-0691-11e8-9692-50acab103591.png)

**IE Waterfall**
![ie-error](https://user-images.githubusercontent.com/30042849/35625097-5d1e47fc-0691-11e8-9288-6b883f92c6dc.png)

Now i followed through the installation guide for the agent. Chrome and Firefox work just fine. Do you have any ideas what the problem might be?

Greetings,
Phil

**Comment by pmeenan** [comment]
Can you reproduce it on the public instance (Dulles or Dulles_Thinkpad)?  If so that would make it easier for me to debug.

Which Windows 10 release?  Is it running the fall creators update?

Are you running the latest code from git master or are you using the last release (there have been quite a few updates for Edge since then)?

If you add ?debug=1 when going to the landing page to run the test (i.e. www.webpagetest.org/?debug=1) or pass debug=1 as a test option through the API then the agent will capture the debug log and upload it with the test (link to download will be to the left of the waterfall).  That would help debug the issue.

**Comment by PhilAlbrecht** [comment]
Unfortunately I cant reproduce the behavior on public instances.
I am running Windows10 Version 1709, which should be the fall creators update.
The computer is running your suggested batch script, which pulls the latest version from the master everytime it starts.

And here is the debug log
[google_com_edge.log](https://github.com/WPO-Foundation/wptagent/files/1695996/google_com_edge.log)

**Comment by PhilAlbrecht** [comment]
Hey there again,

so i finally had time to work on the issue again. Turns out, all i had to do was set the windows language to english (previous german) because IE/Edge use the system language and the events seem to be translated(?). I am fine if you want to close this issue. Just so if anyone encounters the same problem - 
**If Document Complete Time is --- and your test runs into time out on IE/Edge only try setting your system language to english**

kind regards!
