### ISSUE TITLE
Can wptagent start on centos without desktop version?

### ISSUE THREAD

**Issue by cpselvis** [WPO-Foundation/wptagent#82]
After I install firefox with
```
$ yum install firefox
```

After start testing, it throws a error:
![image](https://user-images.githubusercontent.com/18289264/36625342-adc04794-1958-11e8-92f7-3d8967b4eb49.png)

First View: Test Error: Invalid browser - Firefox

**Comment by pmeenan** [comment]
It's probably just a matter of not finding the binary because it doesn't know what path to look for on centos (I did all of the dev and testing on ubuntu).  I'll spin up a centos VM and take a look.

**Comment by pmeenan** [comment]
Yep, it was just that Firefox was at a different path.  It is fixed now.

I also created a [centos version of the install script](https://github.com/WPO-Foundation/wptagent/blob/master/centos_install.sh) that takes care of installing all of the dependencies (and also installs Chrome, Chrome Beta and Chrome Canary).

I tested Chrome (all 3), Firefox and Opera and they are all working well and traffic-shaping is also working so it should be all set.  I have not tested Firefox nightly or opera beta/nightly mostly because there aren't yum repositories for them and installing ins a rather manual process.  If you do need those let me know and I can add them (I'm sure it's just a matter of the path).
