### ISSUE TITLE
Chrome 65 reports strange timing info for blocked requests

### ISSUE THREAD

**Issue by wildlyinaccurate** [WPO-Foundation/wptagent#92]
[This test](https://www.webpagetest.org/result/180323_RM_4832c69d1bb3b0d088e9d0ef52db7e6d/1/details/#waterfall_view_step1) is showing some strange results. I'm fairly certain that this only started to happen in Chrome 65 but I'm not sure if there's an easy way to run a test on Chrome 64 to confirm/deny this.

The requests that are appearing before the HTML document request are all blocked because of a `blockDomainsExcept` command.

![screenshot from 2018-03-23 14-59-33](https://user-images.githubusercontent.com/794263/37807533-d5c06e6a-2eaa-11e8-890f-1a98d2583d7e.png)

**Comment by wildlyinaccurate** [comment]
Ah, this is interesting: [using the `block` command instead](https://www.webpagetest.org/result/180323_QT_1bcab8fbfba705d1fb69834b51eeb91f/1/details/#waterfall_view_step1) to manually block those requests works as expected, i.e. the requests don't show up in the waterfall at all.

![screenshot from 2018-03-23 15-04-22](https://user-images.githubusercontent.com/794263/37807660-7d330ca2-2eab-11e8-9285-96e32f3a4b9a.png)

**Comment by pmeenan** [comment]
Probably a bug in the parsing of the request data from the dev tools interface.  Looking into it now.

"block" uses direct support for blocking requests from ever happening.  "blockDomainsExcept" uses an extension to block the requests but by the time they get to the extension the browser officially "started" the request.  The cancellation is probably not being seen correctly so hopefully it's a quick fix.

The weird timing is something you see for requests that use the timing data from the dev tools interface and not the better timing from the netlog.  Fundamentally it may make sense to just strip away any requests that were not seen in the netlog since they didn't actually hit the network.  Right now it uses both as a failsafe in case something breaks with the netlog parsing.

**Comment by pmeenan** [comment]
[Fix](https://github.com/WPO-Foundation/wptagent/commit/1e46eeab63fb2b8821ff8070827e441273e0ed8f) is rolling out now and should be live across all agents within the next hour.  blockDomainsExcept does the blocking by mapping all domains to localhost except for those that are allowed so they end up as real requests that fail right away (avoids the CPU overhead of using an extension for Chrome which is crazy-expensive).

The fix both looks for the refused connections in the dev tools requests and ignores them and also removes any requests that are in dev tools logs but not the netlog.

![image](https://user-images.githubusercontent.com/444165/37832766-f0063ea6-2e7f-11e8-9245-ed8413c83d4f.png)

**Comment by wildlyinaccurate** [comment]
Looks good to me - thank you!
